version: '3.7'

networks:
  redis-cluster-compose:
    driver: bridge
    ipam:
      config:
        - subnet: 182.17.0.0/16

services:

  redis-node-1:
    image: redis:latest
    ports:
      - "7000:7000"
    networks:
      redis-cluster-compose:
        ipv4_address: 182.17.0.2
    hostname: redis-node-1
    volumes:
      - ./7000:/redis
    command: redis-server /redis/redis.conf

  redis-node-2:
    image: redis:latest
    ports:
      - "7001:7001"
    networks:
      redis-cluster-compose:
        ipv4_address: 182.17.0.3
    hostname: redis-node-2
    volumes:
      - ./7001:/redis
    command: redis-server /redis/redis.conf

  redis-node-3:
    image: redis:latest
    ports:
      - "7002:7002"
    networks:
      redis-cluster-compose:
        ipv4_address: 182.17.0.4
    hostname: redis-node-3
    volumes:
      - ./7002:/redis
    command: redis-server /redis/redis.conf

  redis-node-4:
    image: redis:latest
    ports:
      - "7003:7003"
    networks:
      redis-cluster-compose:
        ipv4_address: 182.17.0.5
    volumes:
      - ./7003:/redis
    command: redis-server /redis/redis.conf

  redis-node-5:
    image: redis:latest
    ports:
      - "7004:7004"
    networks:
      redis-cluster-compose:
        ipv4_address: 182.17.0.6
    hostname: redis-node-5
    volumes:
      - ./7004:/redis
    command: redis-server /redis/redis.conf

  redis-node-6:
    image: redis:latest
    ports:
      - "7005:7005"
    networks:
      redis-cluster-compose:
        ipv4_address: 182.17.0.7
    hostname: redis-node-6
    volumes:
      - ./7005:/redis
    command: redis-server /redis/redis.conf

  redis-cluster-creator:
    image: redis:latest
    ports:
      - "6999:6999"
    networks:
      - redis-cluster-compose
    command: redis-cli -p 7000 --cluster create redis-node-1:7000 redis-node-2:7001 redis-node-3:7002 redis-node-4:7003 redis-node-5:7004 redis-node-6:7005 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    networks:
      - redis-cluster-compose
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis-cluster-creator

  mysql-8.0.32:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: 'orderDevDb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - '13306:3306'
    networks:
      redis-cluster-compose:
        ipv4_address: 182.17.0.8

  eureka:
    image: eureka
    ports:
      - "8761:8761"
    networks:
      redis-cluster-compose:
        ipv4_address: 182.17.0.9

  config-server:
    image: config-server
    ports:
      - "8085:8085"
    expose:
      - "8085"
    links:
      - redis-cluster-creator
    restart: always
    networks:
      - redis-cluster-compose

  api-gateway:
    image: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka
    restart: always
    networks:
      redis-cluster-compose:
        ipv4_address: 182.17.0.10

  order-service:
    image: order
    ports:
      - "8080:8080"
    depends_on:
      - mysql-8.0.32
      - redis-cluster-creator
      - config-server
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    links:
      - mysql-8.0.32
      - redis-cluster-creator
      - config-server
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    restart: always
    networks:
      - redis-cluster-compose