eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always